server:
  port: 9001
spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296
  application:
    name: security-mservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400
